# Generated by Django 2.1.3 on 2018-11-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.User'),
        ),
        migrations.AlterField(
            model_name='recommendationforuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.User'),
        ),
        migrations.AlterField(
            model_name='recommendationpeoplebuy',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_bought', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='recommendationsimilarcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_similar', to='api.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='courseuser',
            unique_together={('course', 'user')},
        ),
    ]
