# Generated by Django 2.1.3 on 2018-11-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181117_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
