export const FETCHED_TRENDING = 'FETCHED_TRENDING';
export const FETCHED_MY_COURSES = 'FETCHED_MY_COURSES';
export const FETCHED_MY_COURSE = 'FETCHED_MY_COURSE';
export const FETCHED_COURSE = 'FETCHED_COURSE';
export const FETCHED_SIMILAR_COURSE = 'FETCHED_SIMILAR_COURSE';
export const FETCHED_SIMILAR_COURSE_FOR_USER = 'FETCHED_SIMILAR_COURSE_FOR_USER';
export const RESET_SIMILAR_COURSE = 'RESET_SIMILAR_COURSE';
export const RESET_SIMILAR_COURSE_FOR_USER = 'RESET_SIMILAR_COURSE_FOR_USER';
